# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: Scratch 3 OneGPIO Extensions
repo_url: https://github.com/MrYsLab/s3-extend/
site_url: https://mryslab.github.io/s3-extend/
copyright: > # should remain a link to the original theme
  Copyright &copy; 2019-2025 Alan Yorinks &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  Last 
  Modified:
  Nov 9, 2025
  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;For Software Versions: &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; s3-extend: 1.30 &nbsp;&nbsp;&nbsp; s3onegpio 1.30
markdown_extensions:
    - tables

nav:
      - Welcome: index.md
      - Preparing Your Computer:
        - Verify/Install Python 3.8: python_3_8_install.md
        - Verifying/Install pip3: pip_update.md
        - Install s3-extend: s3-extend.md
      - Preparing Your Micro-Controller:
        - Arduino And RoboHAT MM1: arduino.md
        - Circuit Playground Express: cpx.md
        - ESP-8266: esp-8266.md
        - ESP-32: esp-32.md
        - Picoboard: pico.md
        - Raspberry Pi: rpi.md
        - Raspberry Pi Pico: rpi_pico.md
      - Ready, Set, Go:
        - How To Use The OneGPIO Extensions: usage.md
        - Starting the Python Extension Servers:
          - Arduino: ext_ard.md
          - Circuit Playground Express: ext_cpx.md
          - ESP-32: ext_esp32.md
          - ESP-8266: ext_esp.md
          - Picoboard: ext_pico.md
          - Raspberry Pi: ext_rpi.md
          - Raspberry Pi Pico: ext_rpi_pico.md
          - RoboHAT MMI: ext_rh.md
        - Shutting Down The Python Extension Servers:
          - Performing A Clean Shutdown: shutdown.md
        - Launching TheScratch 3 Editor:
          - A Word About Browser Compatibility: browsers.md
          - Starting Scratch3 Online: s3-web.md
          - Starting Scratch3 Offline: s3-local.md
        - Using OneGPIO Extension Blocks:
          - Arduino: ard_blocks.md
          - Circuit Playground Express: cpx_blocks.md
          - ESP-32: esp_32_blocks.md
          - ESP-8266: esp_blocks.md
          - Picoboard: pico_blocks.md
          - Raspberry Pi: rpi_blocks.md
          - Raspberry Pi Pico: rpi_pico_blocks.md
          - RoboHAT MM1: robohat_blocks.md
      - Tips And Techniques:
          - When In Doubt, Add A Small Delay: delay.md
          - Running Multiple OneGPIO Extensions Simultaneously: multi.md
      - A Peek Under The Hood:
          - The OneGPIO Gateways and Launchers: under_the_hood.md
      - Want To Contribute A Language Translation?:
          - Contributing Block Translations: translate.md
      - Acknowledgments:
          - Thank You: acks.md
      - Need Help?:
        - Reporting Issues: issues.md

theme:
  name: 'material'
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.footer

plugins:
  - search

